bot:
  automerge: true
conda_forge_output_validation: true
provider:
  linux:
    - azure
    - github_actions
  linux_aarch64: azure
  linux_ppc64le: azure
  osx: circle
  win: azure

github_actions:
  self_hosted: true
